default_agent: scensei
agents:
  scensei:
    name: scensei
    language: python
    node_version: '20'
    entrypoint: /Users/Naoki/work/workshop/scensei/agentcore/app.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/Naoki/work/workshop/scensei/agentcore
    aws:
      execution_role: arn:aws:iam::765653276628:role/AmazonBedrockAgentCoreSDKRuntime-ap-northeast-1-f94973b5b0
      execution_role_auto_create: false
      account: '765653276628'
      region: ap-northeast-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-765653276628-ap-northeast-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: scensei-xajQ0R77kv
      agent_arn: arn:aws:bedrock-agentcore:ap-northeast-1:765653276628:runtime/scensei-xajQ0R77kv
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: scensei_mem-INEd7K94yX
      memory_arn: arn:aws:bedrock-agentcore:ap-northeast-1:765653276628:memory/scensei_mem-INEd7K94yX
      memory_name: scensei_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_9YLOHAYn6/.well-known/openid-configuration
        allowedClients:
        - 1qemnml5e11reu81d0jap2ele3
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
